syncfusion/blazor-locale

src/SfResources.nl.resx

Modified the locale changes for Dialog and Toast in nl culture

Changed locale changes for Dialog and Toast

---

src/SfResources.de.resx

Have modifed the locale words changes for the Rich Text Editor.

Updated the German words for the Rich Text Editor

---

src/SfResources.de.resx

bug(BLAZ-9666): Updated the PDF Viewer localization content

bug(BLAZ-9666): Updated the PDF Viewer localization content

---

src/SfResources.pt.resx

bug(BLAZ-9595): Remove excess ungroup in Pt locale.

bug(BLAZ-9595): Remove excess ungroup

---

src/SfResources.fa.resx
src/SfResources.ms.resx
src/SfResources.nb.resx
src/SfResources.pt.resx

Reverts syncfusion/blazor-locale#28

Revert "Persian locale changes in grid"

---

src/SfResources.pt.resx

Fixed some translation mistakes...

Portuguese translation corrections

---

src/SfResources.ar.resx
src/SfResources.de.resx
src/SfResources.en-GB.resx
src/SfResources.en-US.resx
src/SfResources.es.resx
src/SfResources.fa.resx
src/SfResources.fi.resx
src/SfResources.fr-CH.resx
src/SfResources.fr.resx
src/SfResources.he.resx
src/SfResources.hr.resx
src/SfResources.hu.resx
src/SfResources.it.resx
src/SfResources.ja.resx
src/SfResources.ko.resx
src/SfResources.ms.resx
src/SfResources.nb.resx
src/SfResources.nl.resx
src/SfResources.pt.resx
src/SfResources.resx
src/SfResources.ro.resx
src/SfResources.ru.resx
src/SfResources.th.resx
src/SfResources.tr.resx
src/SfResources.vi.resx
src/SfResources.zh.resx

Pivot Table localization changes - updated.

bug(BLAZ-18402): Pivot Table localization changes - updated.

---

src/SfResources.de.resx
src/SfResources.en-US.resx
src/SfResources.fa.resx
src/SfResources.fr-CH.resx
src/SfResources.zh-TW.resx

Update Latest Release V19.4.38 Changes

Update Latest Release V19.4.38 Changes

---

src/SfResources.de.resx

Save word for German culture in Schedule has been changed properly

Save word for German culture in Schedule has been changed

---

src/SfResources.de.resx

config(BLAZ-17161): update localization for No record template content

Update localization for No record template

---

src/SfResources.de.resx

customer-provided locale constants changes and committed,
https://github.com/syncfusion/blazor-locale/pull/42/files

bug(BLAZ-19759): Blazor Grid locale changes for de

---

src/SfResources.de.resx

Blazor File Manager, save button localized text is updated for the de culture.

Blazor File Manager component, save button localized text is updated for de culture.

---

src/SfResources.cs.resx
src/SfResources.da.resx
src/SfResources.fa.resx
src/SfResources.nb.resx

Update Latest Release V19.4.48 Changes

Update Latest Release V19.4.48 Changes

---

src/SfResources.tr.resx

changed locale names for few Gantt properties

bug(Blaz-20117): locale corrections for gantt

---

src/SfResources.tr.resx

Locale corrections for file manager and range slider components

Locale corrections for file manager and range slider components

---

src/SfResources.fr-CH.resx
src/SfResources.fr.resx

Reviewed and updated https://github.com/syncfusion/blazor-locale/pull/81 and updated `French` locale values in Resource file
[French-Locale.zip](https://github.com/syncfusion/blazor-locale/files/10092602/French-Locale.zip)

Updated Values for French Locale

---

src/SfResources.de.resx
src/SfResources.it.resx

Reviewed and updated https://github.com/syncfusion/blazor-locale/pull/74 and updated `French` locale values in Resource file
[Italian-Locale.zip](https://github.com/syncfusion/blazor-locale/files/10092652/Italian-Locale.zip)

Reviewed and updated #74 and updated French locale values in Resource file

---

src/SfResources.de.resx

Reviewed and updated #75 and updated German locale values in Resource file
[German-Locale.zip](https://github.com/syncfusion/blazor-locale/files/10092754/German-Locale.zip)

Reviewed and updated #75 and updated German locale values in Resource file

---

src/SfResources.it.resx

Updated values in italain culture locale values
PR: https://github.com/syncfusion/blazor-locale/pull/87
[Locale-it.zip](https://github.com/syncfusion/blazor-locale/files/10372970/Locale-it.zip)

Update It locale values

---

src/SfResources.fa.resx
src/SfResources.tr.resx

Update locale values for Farsi culture
PR: https://github.com/syncfusion/blazor-locale/pull/77

Updated locale values for Farsi culture

---

src/SfResources.da.resx
src/SfResources.es.resx
src/SfResources.it.resx

Resolved the Localization issues in Form components

Resource file changes for form components

---

src/SfResources.da.resx
src/SfResources.es.resx
src/SfResources.it.resx

Resolved the Localization issues in ListBox, Querybuilder, Colorpicker

bug(828657): Resolved the Localization issues in ListBox, Querybuilder, Colorpicker

---

src/SfResources.da.resx
src/SfResources.es.resx
src/SfResources.it.resx

Hi Kamesh,
I have resolved the localization issues in Danish, Spanish and Italian languages for PDF Viewer component.
Regards,
Ranjitha A.

BLAZ-828631 Localization for Danish, Spanish and Italian languages have been completed for PDF Viewer component.

---

src/SfResources.nl.resx

Translate Doorzichtig into Wissen in Dutch

bug(BLAZ-828237) : Dutch Translate issue is fixed.

---

src/SfResources.da.resx
src/SfResources.es.resx
src/SfResources.it.resx

Updated Localization for blazor Chart.

bug(825793): Updated Localization for blazor Chart.

---

src/SfResources.da.resx
src/SfResources.es.resx
src/SfResources.it.resx

Hi @Keerthivasan-Ramamoorthy sir,
Updated PR for Danish, Panish, Italian language content changes. Can you please review this PR?
Regards,
Kiruthika M

BLAZ-826028-LocaleContentChanges

---

src/SfResources.it.resx

Update the update Italian translations for Diagram Component.

Bug(ES-839930): Update SfResources.it.resx file

---

src/SfResources.it.resx

Hi Kamesh,
I have updated the locale changes for PDF Viewer component. Can you please review the changes?
Regards,
Ranjitha A.

BLAZ-839987 Locale changes for PDF Viewer component.

---

src/SfResources.it.resx

Update the Italian translations for Schedule, Carousel, Tabs and RecurrenceEditor Component.

bug(ES-839941-localeWords): Ensure the localization for english to italian words.

---

src/SfResources.it.resx

config(840015): Update Italian locale text

---

src/SfResources.it.resx

Committed words equivalent to Italian translation.

bug(Blaz-839688): Committed words equivalent to italian translation.

---

src/SfResources.es.resx

- Removed the unwanted tag from 'SfResources.es.resx' resource file.

spanish resource changes

---

src/SfResources.ca.resx

- To Add catalan localization for syncfusion blazor components

added catalan localization

---

src/SfResources.de.resx

bug(509029) - Localization issue in German culuture has been resolved

bug(509029) - Localization issue in German culuture has been resolved

---

src/SfResources.fr.resx

Pâte means pasta.
(EN) to paste = (FR) coller
#128

FR : pâte -> coller

---

src/SfResources.pt-BR.resx

- BRAZIL localization support to Syncfusion Blazor components.(Portuguese - BRAZIL)

config(BLAZ-856653): To add portuguese brazil localization.

---

src/SfResources.he.resx

###Description
Resolving the syntax error in SfResources.he.resx

895555: Resolved syntax error

---

src/SfResources.es.resx

bug(892951): Localization issue in spanish culuture has been resolved

bug(892951): Localization issue in spanish culuture has been resolved.

---

src/SfResources.fr.resx

Provided the correct translations for reported text in French localization.

Resolved incorrect translations in French.

---

src/SfResources.fr-CH.resx
src/SfResources.fr.resx

Description:
Need to correct the French localization text for the SelectedItems.

Need to correct the French localization text for the SelectedItems.

---

src/SfResources.de.resx

Need to correct the German localization for FileManager component

Need to correct the German localization for FileManager component

---

src/SfResources.vi.resx

description:
Remove unsued values in RichtextEditor

Remove unsued values in RichtextEditor
